import{a as L,S as v,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))d(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const w=L.create({baseURL:"https://pixabay.com/api/"});async function u(o,t){return(await w.get("",{params:{key:"50364096-1c7ce5aa76102baff0b747707",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const m=document.querySelector(".gallery"),c=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");console.log("Значення myLoader при завантаженні скрипту:",c);let S=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function p(o){const t=o.map(s=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s.largeImageURL}">
          <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" />
        </a>
        <div class="info">
        <p class="info-item"><span class="label">Likes:</span> ${s.likes}</p>
        <p class="info-item"><span class="label">Views:</span> ${s.views}</p>
        <p class="info-item"><span class="label">Comments:</span> ${s.comments}</p>
        <p class="info-item"><span class="label">Downloads:</span> ${s.downloads}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){m.innerHTML=" "}function y(){c.classList.add("visible")}function g(){c.classList.remove("visible")}function E(){f.classList.remove("is-hidden")}function h(){f.classList.add("is-hidden")}const P=document.querySelector(".form"),$=document.querySelector('[name="search-text"]');document.querySelector("button");const B=document.querySelector(".load-more-btn");let n="",i=1;const b=15;P.addEventListener("submit",I);B.addEventListener("click",M);async function I(o){if(o.preventDefault(),n=$.value.trim(),n===""){a.error({title:"Error",message:"Please enter valid values"});return}q(),y(),h(),i=1;try{const t=await u(n);if(t.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(t.hits),t.totalHits>b&&E()}catch{a.error({title:"Error",message:"Something went wrong. Try again!"})}finally{g()}}async function M(){i+=1,y();try{const o=await u(n,i);p(o.hits),i*b>=o.totalHits&&(h(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Failed to load more images."})}finally{g()}}
//# sourceMappingURL=index.js.map
