import{a as L,S as v,i as a}from"./assets/vendor-frHSA4Lh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&d(l)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function d(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const w=L.create({baseURL:"https://pixabay.com/api/"});function u(s,r){return w.get("",{params:{key:"50364096-1c7ce5aa76102baff0b747707",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}})}const m=document.querySelector(".gallery"),c=document.querySelector(".loader"),f=document.querySelector(".load-more-btn");console.log("Значення myLoader при завантаженні скрипту:",c);let S=new v(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function p(s){const r=s.map(e=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${e.largeImageURL}">
          <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
        </a>
        <div class="info">
        <p class="info-item"><span class="label">Likes:</span> ${e.likes}</p>
        <p class="info-item"><span class="label">Views:</span> ${e.views}</p>
        <p class="info-item"><span class="label">Comments:</span> ${e.comments}</p>
        <p class="info-item"><span class="label">Downloads:</span> ${e.downloads}</p>
        </div>
      </li>
    `).join("");m.insertAdjacentHTML("beforeend",r),S.refresh()}function q(){m.innerHTML=" "}function y(){c.classList.add("visible")}function g(){c.classList.remove("visible")}function E(){f.classList.remove("is-hidden")}function h(){f.classList.add("is-hidden")}const P=document.querySelector(".form"),$=document.querySelector('[name="search-text"]');document.querySelector("button");const B=document.querySelector(".load-more-btn");let n="",i=1;const b=15;P.addEventListener("submit",I);B.addEventListener("click",M);async function I(s){if(s.preventDefault(),n=$.value.trim(),n===""){a.error({title:"Error",message:"Please enter valid values"});return}q(),y(),h(),i=1;try{const e=(await u(n)).data;if(e.hits.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}p(e.hits),e.totalHits>b&&E()}catch{a.error({title:"Error",message:"Something went wrong. Try again!"})}finally{g()}}async function M(){i+=1,y();try{const r=(await u(n,i)).data;p(r.hits),i*b>=r.totalHits&&(h(),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}));const{height:e}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch{a.error({title:"Error",message:"Failed to load more images."})}finally{g()}}
//# sourceMappingURL=index.js.map
